added card photo , social links
razvancir96/itschool-students-gen1 pull request #1
Opened 2021-08-24 18:15 UTC by GmdDaniel

lipsa de inspiratie pe partea de descriere :)

2021-09-10 11:04 UTC, razvancir96 requested changes

2021-09-10 11:04 UTC, razvancir96 commented on index.html
> +                                <a href="https://codepen.io/your-work"><img src="assets/codepen.svg" alt="codepen"></a>
Link-ul de CodePen nu este valid. Ar trebui sa arate sub forma asta: https://codepen.io/razvan-cirlugea

2021-09-10 11:04 UTC, razvancir96 commented on index.html
> +                                <img src="https://media-exp1.licdn.com/dms/image/D4E35AQHPzG3qUwWeqw/profile-framedphoto-shrink_400_400/0/1621412650379?e=1629918000&v=beta&t=QZ2qGpQWdUvhnGAiHsmnyVT9S
Am incercat sa vad imaginea, insa imi da "access denied".

2021-09-10 11:04 UTC, razvancir96 commented on index.html
>                                  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae omnis nobis quo dicta culpa eum
Ca sa pot da merge la pull request, o sa te rog sa adaugi si o descriere 😛

2021-09-12 10:03 UTC, GmdDaniel commented on index.html
>                                  <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestiae omnis nobis quo dicta culpa eum
done

2021-10-23 14:33 UTC, closed without merging